# Copied from: https://github.com/hvr/multi-ghc-travis
language: c

# explicitly request container-based infrastructure
sudo: false

cache:
 directories:
 - $HOME/.cabal

matrix:
  include:
    - env: CABALVER=1.18 GHCVER=7.6.3
      addons: {apt: {packages: [cabal-install-1.18,ghc-7.6.3], sources: [hvr-ghc]}}
    - env: CABALVER=1.18 GHCVER=7.8.4
      addons: {apt: {packages: [cabal-install-1.18,ghc-7.8.4], sources: [hvr-ghc]}}
    - env: CABALVER=1.22 GHCVER=7.10.3
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.3],sources: [hvr-ghc]}}
    - env: CABALVER=1.24 GHCVER=7.10.3 MAYBE_GHCJS=--ghcjs
      addons: {apt: {packages: [cabal-install-1.24,ghc-7.10.3,happy-1.19.5],sources: [hvr-ghc]}}
    - env: CABALVER=1.24 GHCVER=8.0.1
      addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.1], sources: [hvr-ghc]}}
    - env: CABALVER=head GHCVER=head
      addons: {apt: {packages: [cabal-install-head,ghc-head],  sources: [hvr-ghc]}}

  allow_failures:
   - env: CABALVER=head GHCVER=head

before_install:
 - export PATH=$HOME/.cabal/bin:/opt/happy/1.19.5/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
 - travis_retry cabal update
 - sed -i 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config
 - test -z "$MAYBE_GHCJS" || (test -x $HOME/.cabal/bin/ghcjs  || (cabal install -j2 http://ghcjs.luite.com/master.tar.gz && ghcjs-boot --no-prof --no-haddock -j2))
 - cabal install -j2 $MAYBE_GHCJS --only-dependencies --enable-tests -fdev

script:
 - cabal configure $MAYBE_GHCJS -fdev --enable-tests -finstrumented
 - cabal build
 - dist/build/tests/tests
